name: Deploy to DigitalOcean Droplet1
"on":
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.1
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Copy files
        run: rsync -av --exclude='./node_modules/*' ./ /var/www/test-vuejs
